function [depthRight, pFRight, pTauRight, pHLRight, pFLRight, psLRight, ...
          depthLeft, pFLeft, pTauLeft, pHLLeft, pFLLeft, psLLeft, ...
          idxQSRight, pFsQSRight, pHLsQSRight, pFLsQSRight, psLsQSRight, ...
          idxQSLeft, pFsQSLeft, pHLsQSLeft, pFLsQSLeft, psLsQSLeft ...
         ] = reoCalculateSubtrQS(hLib, H, T, D, freq, harms, taus, tau1idx, mask, tol)

gstSetPreferenceInt(hLib, 'cycloCalc.ConsiderFreeFree', 1);
gstSetPreferenceInt(hLib, 'cycloCalc.ConsiderFreeFree.Only', 0);
[depthRight, pFRight, pTauRight, pHLRight, pFLRight, psLRight, ...
 depthLeft, pFLeft, pTauLeft, pHLLeft, pFLLeft, psLLeft] = ...
    reoCalculate(hLib, H, T, D, freq, harms, taus, mask);

gstSetPreferenceInt(hLib, 'cycloCalc.ConsiderFreeFree.Only', 1);
[depthRightFF, pFRightFF, pTauRightFF, pHLRightFF, pFLRightFF, psLRightFF, ...
 depthLeftFF, pFLeftFF, pTauLeftFF, pHLLeftFF, pFLLeftFF, psLLeftFF] = ...
    reoCalculate(hLib, H, T, D, freq, harms, taus, mask);

[idxQSRight, pFsQSRight, pHLsQSRight, pFLsQSRight, psLsQSRight] = l_subtr(tol ...
      , depthRight, pFRight, pTauRight, pHLRight(:,:,tau1idx), pFLRight(:,:,tau1idx), psLRight(:,:,tau1idx) ...
      , depthRightFF, pFRightFF, pTauRightFF, pHLRightFF(:,:,tau1idx), pFLRightFF(:,:,tau1idx), psLRightFF(:,:,tau1idx));
[idxQSLeft, pFsQSLeft, pHLsQSLeft, pFLsQSLeft, psLsQSLeft] = l_subtr(tol ...
      , depthLeft, pFLeft, pTauLeft, pHLLeft(:,:,tau1idx), pFLLeft(:,:,tau1idx), psLLeft(:,:,tau1idx) ...
      , depthLeftFF, pFLeftFF, pTauLeftFF, pHLLeftFF(:,:,tau1idx), pFLLeftFF(:,:,tau1idx), psLLeftFF(:,:,tau1idx));

end

%--------------------------------------------------------------------------
function [idxQS, pFsQS, pHLsQS, pFLsQS, psLsQS] = l_subtr(tol ...
               , depth, pF, pTau, pHL, pFL, psL ...
               , depthFF, pFFF, pTauFF, pHLFF, pFLFF, psLFF)
             
v = (pF - pFFF)./pFFF;
v(isnan(v)) = 0;
idxQS = v < tol;
             
pFsQS = pF;
pFsQS(idxQS) = 0;
pHLsQS = pHL;
pHLsQS(idxQS) = 0;
pFLsQS = pFL;
pFLsQS(idxQS) = 0;
psLsQS = psL;
psLsQS(idxQS) = 0;

end
